// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztkdnigyjzlpjfoapvmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0a2RuaWd5anpscGpmb2Fwdm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMDU3MjUsImV4cCI6MjA1NjU4MTcyNX0.5FeoLaZg827ODLWpy59yQ4vYD5J-qMnLI7dsUQMI0LA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);